FROM python:3.12.1-alpine3.18 # Базовый образ

WORKDIR /usr/workspace # Рабочая директория

COPY ./ /usr/workspace # Копируем все файлы в образ

RUN pip3 install requests # Устанавливаем requests

CMD ["python3", "insult.py"] # Команда запуска программы